- src/main.ts
Adding `popstate` keeps Obsidian from creating new history entries for a different view on the same file.
> Fix #132 (extra history entries from mode switch)

- package.json
- rollup.config.js
- tsconfig.json
- yarn.lock
Removing babel and updating the TypeScript build target shaves a few seconds off of builds and shrinks the output size of the plugin.  It may also have a positive effect on performance, as some JS language or library features will use native implementations instead of TS/Babel-supplied emulations.
> Speed and streamline build (es2018 + no babel)

- src/components/Item/ItemForm.tsx
- src/components/Kanban.tsx
- src/components/Lane/Lane.tsx
- src/components/types.ts
Drop or paste any of the following into the "+ Add a card" area of a lane, to add one or more cards:
* File(s) (single or multi) from the explorer pane
* Files from plugins whose views support it (stars, recent-files, pane-relief history, backlinks, etc.)
* Internal and external links from any preview (including page previews and dataview-generated links)
* HTML, plain text, and URLs from anywhere in Obsidian and from other apps.
HTML is converted to markdown, unless you've disabled that in Obsidian's config, or if you hold shift while dropping.  Every line, paragraph, file, or link becomes a separate card.  (Or in the case of pasting, if there's only one line of text, it's pasted in the textarea as usual.)
> Create cards by dropping or pasting links, text, or file(s) into "Add a card" area

- src/DataBridge.ts
- src/DragDropApp.tsx
- src/KanbanView.tsx
- src/components/Kanban.tsx
- src/components/Lane/Lane.tsx
- src/components/helpers.ts
- src/main.ts
Cards and lanes can be dragged between board views.  (Note that dragging between boards can break links, depending on your Obsidian link settings and whether you have notes with the same name in different locations.)
This is a significant re-organization and should probably be tested more thoroughly, as I only use a fraction of the plugin's features and might not notice if I broke something.
> Implement #31: Drag and drop between boards

- src/components/Item/Item.tsx
This PR adds CSS classes `has-tag-[tagname without # symbol]` to each card. This can be useful for styling cards and customise display to address use cases such as snoozing cards (cf. #138).
> Add tag-specific classes.

- src/DataBridge.ts
- src/DragDropApp.tsx
- src/KanbanView.tsx
- src/components/Kanban.tsx
- src/main.ts
These changes should fix some of the problems, *possibly* including #178.
Regarding performance, the first level of fixes I know how to do are parsing/unparsing (boardToMd/mdToBoard).  Specifically, the parser needs to maintain incremental state, so that item IDs are fixed (to prevent re-rendering the whole board for every change) and to avoid the need to parse lines that haven't changed.  I've already got a draft of that, but it needs some cleanup.
A complicating factor is the board settings.  Right now everything is basically using a typed bag of props and dynamically determining defaults, and it's not clear to me whether everything updates correctly when you change settings.  (Or conversely, if settings actually update *too often*.)
To summarize the future plans: I'd like to 
1. Make …
> Misc fixes for file/state updating and refreshing

- src/KanbanView.tsx
The code for saving settings was relying on the double-updating bug in the Kanban component.
> Fix #200 - Settings not being saved

- package.json
- src/KanbanView.tsx
- src/components/Item/Item.tsx
- src/components/Item/ItemContent.tsx
- src/components/Item/ItemForm.tsx
- src/components/Item/ItemMenu.ts
- src/components/Item/helpers.ts
- src/components/Kanban.tsx
- src/components/Lane/Lane.tsx
- src/components/Lane/LaneForm.tsx
- src/components/Lane/LaneHeader.tsx
- src/components/Lane/LaneSettings.tsx
- src/components/Lane/LaneTitle.tsx
- src/components/MarkdownRenderer.tsx
- src/components/context.ts
- src/components/types.ts
- src/lang/locale/en.ts
- src/main.ts
- src/parser.ts
- yarn.lock
So this is basically a branch to refactor the parser.  Why?
Well, parser performance is a significant part of initial view load, which can currently take multiple seconds for a board with a few hundred items.  Raw parse speed is a big part of that.
But it's also even more important for fixing #172, which requires using Obsidian's quick-preview events mechanism to co-ordinate updates between text files.  Currently, the blocker on using that is the fact that quick-preview basically means lots more parsing (at least when there is more than one view on the file open).  A simple caching mechanism to implement incremental parsing gets rid of most of the quick-preview overhead, but requires the parser to keep state.  (My original hack attempt at this kept that state in the view and passed it in …
> Parser refactoring (WIP but merge any time)

- src/KanbanView.tsx
- src/lang/locale/en.ts
- src/parser.ts
* split() issue (new from #199)
* Wasn't handling non-task items (new from #199)
* Error if no first lane header (pre-existing issue)
* Was silently discarding lines it didn't understand (pre-existing issue)
* Didn't support empty-titled headings (even though you could create them!)  (pre-existing issue)
* Error handler caused a blank display instead of showing an error message if loading a file failed on first parse (not sure how far back this one goes)
* Added text to error handler to suggest editing the file as a fix
> Parser fixes: more robust parsing, fix some outstanding issues

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
I added Issueforms for both Bug Reports and Feature Requests. This will help a lot with Bug Reports, because Users know what you need to fix it. 
If you want to preview how they look, you can test it on the Dictionary Plugin Repo: https://github.com/phibr0/obsidian-dictionary/issues/new/choose
> Add Issueforms for easier Bug Reports and Feature Requests

- src/helpers/renderMarkdown.ts
This fixes the underlying parsing problems of Issue #456 explained in https://github.com/mgmeyers/obsidian-kanban/issues/456#issuecomment-1027932480 by reordering the string splitting operations.
Before this change the order was '#' (subpath) first, then '|' (alias). This led to the following problem:
Link:          [[TestCard|Hash # and Pipe | in alias]]
splitOnHash:     └──────0─────┘^└────────1─────────┘
splitOnAlias:                   └────0───┘^└───1───┘
Result:          └────root────┘ └#subpath┘ └─alias─┘
Inverting the order results in the correct parsing:
Link:          [[TestCard|Hash # and Pipe | in alias]]
splitOnAlias:    └──0───┘^└───────────1────────────┘
splitOnHash:     └──0───┘
Result:          └─root─┘ └─────────alias──────────┘ with empty subpath
These cases are now …
> Fix wikilink path parsing

- src/MetadataSettings.tsx
- src/components/Editor/autocomplete.ts
- src/components/Editor/datepicker.ts
- src/components/Editor/textcomplete/textcomplete-core/Dropdown.ts
- src/components/Editor/textcomplete/textcomplete-textarea/TextareaEditor.ts
- src/components/Item/ItemContent.tsx
- src/components/Item/helpers.ts
- src/dnd/components/DragOverlay.tsx
- src/dnd/managers/DragManager.ts
This is just making it so that drag-drop works in all windows (but not between windows).  It doesn't address the ctrl-key handlers for checkboxes, or the shift key handler for drops: these only work in the main window at the moment.
To handle them properly, the ItemCheckbox would need to know what window it's in, and the main plugin would need to add shift-tracking handlers to all created windows (e.g. using a PerWindowComponent, as used in Quick Explorer and Hover Editor), or find some other way to get hold of the shift state.
The approach I've taken here is fairly minimalist: making DragOverlay always portal its children to the document.body of the active document.  This makes the assumption that if you're dragging, then the document containing the draggable should've been active.  A …
> Initial multi-window support for 0.15.x (Fix #552)

- src/Settings.ts
- src/TagColorSettings.tsx
- src/components/Item/ItemContent.tsx
- src/components/types.ts
- src/lang/locale/en.ts
- src/main.css
This PR adds the ability to configure colors for display tags, replicating Trello's label functionality.
I'm opening this mostly to get a conversation started. I would love to get your thoughts on this feature. I [asked the Obsidian MD subreddit](https://www.reddit.com/r/ObsidianMD/comments/xcdkn1/would_anyone_be_interested_in_colorful_tags_for/) if this is a feature that would be desired, and the response seemed overwhelmingly positive. The implementation and configurability is still something I'm not certain about.
Here are my main questions:
- Is this a feature you'd want to integrate directly into this plugin?
- Does this implementation make sense to you? I wondered if I should use the existing tag functionality or create a totally new concept like labels. Tags seemed to make more …
> Configurable display tag colors

- src/components/Item/ItemMenu.ts
- src/helpers/boardModifiers.ts
- src/lang/locale/en.ts
- src/lang/locale/zh-cn.ts
Implements the idea proposed in #510 which involves adding 2 new operations in the card's context menu: 
- 'Move to top' moves the card to the top of the lane.
- 'Move to bottom' moves the card to the bottom of the lane.
**Demo**:
https://user-images.githubusercontent.com/54927071/191432600-baea0c05-7ae0-4944-af03-35e4191f41fa.mp4
> Implement move-to-top and move-to-bottom item operations.

- src/KanbanView.tsx
- src/main.ts
Added a getBoardSettings() method to KanbanView.tsx. Also added a command that calls this function for the active view. This allows the user to set their own hotkey to call this method, or call it from the Command Palette, if they have that plugin enabled.
> Added getBoardSettings() method fix #379

- src/parsers/helpers/hydrateBoard.ts
This line fixes this issue. The seconds store in the file were not being passed into the hydrateBoard.ts, now they are!
> Added seconds to the hydrateBoard.ts Fix #197

- manifest.json
I am adding helpUrl to the manifest to support the help system integration into Obsidian. Please consider supporting this initiative. Just so you know, this key value in manifest.json must be in the manifest downloaded as part of the plugin in the release.
https://forum.obsidian.md/t/links-to-help-and-manuals-for-plugins-and-themes/70733/8
> Add helpUrl to manifest.json

- src/Settings.ts
- src/components/MarkdownRenderer/MarkdownRenderer.tsx
- src/lang/locale/en.ts
This video demonstrates the existing "click tag" functionality, and the new "Tag Action" setting which changes the "click tag" functionality:
https://github.com/mgmeyers/obsidian-kanban/assets/134939/3e3d0edc-8750-49e5-a29a-f2a9a0c54217
> [Feature] add setting to search kanban board by clicking tags

- src/components/Item/InlineMetadata.tsx
The previous logic would replace uppercase letters with hyphens, e.g.:
1. `Story Points` would become `-tory--oints`.
2. `storyPoints` would become `story-oints`.
This small PR fixes that, making sure to abide to the spirit of the code, which was to keep keys lowercase.
1. Would we really want to enforce only lowercase letters? The CSS specs allows underscores and uppercase class names.
2. I think the classname for the key should also be prefixed and namespaced, as in the current status it will result in potentially dangerous/non-specific class names. I propose adding the base namespace and then perhaps an extra identifier, something like: `kanban-plugin__item-task-inline-metadata-item__key-${myKey}`.
> Fix inline metadata class names

- src/parsers/helpers/hydrateBoard.ts
I was a bit baffled why the inline metadata was not correctly moved to the footer, even when the options was on, if the metadata was somewhere else in the body of the card. I used to separate some of the inline metadata for clarity and readability, and that surprised me.
I realized the code in `hydrateBoard.ts` was excluding anything outside the first line. I dug a bit in the repo to understand why, and I think—also considering the code—that the spirit of the code was for that to be applied only to `Tasks` metadata, which, being emojis and very peculiar, makes sense as we don't want anything in the body to be captured.
However, I think Dataview metadata was probably intended to be captured, so I fixed that. The new code does:
1. Includes all inline Dataview metadata, regardless of its …
> Fix inline metadata not recognized if not in first line

- src/Settings.ts
- src/StateManager.ts
- src/components/Item/InlineMetadata.tsx
- src/components/Item/Item.tsx
- src/components/Item/MetadataTable.tsx
- src/components/Table/helpers.tsx
- src/components/helpers.ts
- src/lang/locale/en.ts
- src/parsers/common.ts
- src/parsers/helpers/hydrateBoard.ts
- src/settingHelpers.ts
> My last PR for today, I swear! 😅 
> This PR adds a feature I'd love to have, hence it's a bit larger.
This PR introduces a new setting option in the “Move inline metadata to card footer” that allows inline metadata to be displayed (and merged) within the Metadata table at the bottom of the card. This makes it easier to achieve a consistent look between cards whose metadata comes from linked pages and those which have it inline (in my case, I sometimes want to create a card without an attached note, but have the same metadata I'd use within my note YAML).
Because of this change, I renamed the setting to “Inline metadata position” and changed the help text. Also changed the toggle to a dropdown with three options:
1. “Card body” – same as previous setting when it was off.
2. “Card footer” …
> Add support for merging metadata in metadata table
